tables:
- name: application
  priority: 1
  columns:
  - name: application_id
    pattern: "ABC#####"
    parent: true
    validation:
      unique: true 
  - name: created_on
    type: timestamp
    format: "2025-03-07 12:00:00"
    range:
      min: "2025-03-07 12:00:00"
      max: "2025-03-07 12:00:00"
  - name: submitted_date
    type: timestamp
    format: "2025-03-07 12:00:00"
  - name: modified_on
    type: timestamp
    format: "2025-03-07 12:00:00"
  - name: modified_by
    type: string
    value: ["John Doe", "Jane Doe"]
  - name: product_code
    value: ["ABC1", "ABC2"]
  - name: reg_id
    type: int
    range:
      min: 1
      max: 1000
  - name: status
    type: string
    value: ["PENDING", "IN_PROGRESS", "COMPLETED", "REJECTED"]
  - name: priority
    type: string
    value: ["LOW", "MEDIUM", "HIGH"]
  - name: completed_on
    type: timestamp
    format: "2025-03-07 12:00:00"
  - name: metadata
    type: json
    json_config:
    - name: name
      type: string
    - name: age
      type: int
      range:
        min: 18
        max: 65
    - name: email
      type: email
  - name: salary
    type: decimal
    range:
      min: 1000
      max: 100000
  # Cassandra-specific types
  - name: user_preferences
    type: map
    key_type: string
    value_type: string
    map_config:
      min_entries: 2
      max_entries: 5
      keys: ["theme", "language", "notifications"]
      values: ["dark", "light", "en", "fr", "on", "off"]
  - name: tags
    type: set
    element_type: string
    set_config:
      min_elements: 1
      max_elements: 3
      values: ["urgent", "important", "normal", "low"]
  - name: address
    type: udt
    udt_config:
      name: address_type
      fields:
        - name: street
          type: string
        - name: city
          type: string
        - name: state
          type: string
        - name: zip_code
          type: string
          pattern: "#####"
  - name: phone_numbers
    type: list
    element_type: string
    list_config:
      min_elements: 1
      max_elements: 3
      pattern: "+1-###-###-####"
  - name: coordinates
    type: tuple
    tuple_config:
      elements:
        - type: decimal
          range:
            min: -180.0
            max: 180.0
        - type: decimal
          range:
            min: -90.0
            max: 90.0
  rules:
  # Ensure submitted_date is at least 2 hours after created_on
  - when: "fields.submitted_date <= fields.created_on || addDuration(fields.created_on, '2h') > fields.submitted_date"
    then:
      submitted_date: "${addDuration(fields.created_on, '2h')}"
  
  # Set modified_on to 1 hour after created_on
  - when: "true"
    then:
      modified_on: "${addDuration(fields.created_on, '1h')}"
  
  # Set priority based on salary
  - when: "fields.salary > 50000"
    then:
      priority: "HIGH"
    otherwise:
      priority: "${fields.salary > 25000 ? 'MEDIUM' : 'LOW'}"
  
  # Set completed_on based on status
  - when: 'fields.status == "COMPLETED"'
    then:
      completed_on: "${addDuration(fields.modified_on, '2h')}"
  
  # Add validation rules for rejected applications
  - when: 'fields.status == "REJECTED"'
    then:
      completed_on: "${addDuration(fields.modified_on, '30m')}"
      priority: "LOW"
  
  # Complex time arithmetic for in-progress applications
  - when: 'fields.status == "IN_PROGRESS" && fields.priority == "HIGH"'
    then:
      completed_on: "${addDuration(fields.modified_on, '1h')}"
      modified_by: "John Doe"
    otherwise:
      completed_on: "${addDuration(fields.modified_on, '2h')}"
      modified_by: "Jane Doe"

- name: "application_status"
  depends_on: "application"
  columns:
  - name: id
    type: uuid
  - name: application_id
    foreign: "application.application_id"
  - name: reason
    type: sentence
  - name: status
    type: bool